export const INFRASTRUCTURE_TOKENS = {
  DATA_SOURCE: Symbol('DATA_SOURCE'),
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  JWT_TOKEN_GENERATOR: Symbol('JWT_TOKEN_GENERATOR'),
} as const;
