export const INFRASTRUCTURE_TOKENS = {
  DATA_SOURCE: Symbol('DATA_SOURCE'),
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  TENANT_REPOSITORY: Symbol('TENANT_REPOSITORY'),
  TENANT_BILLING_PROFILE_REPOSITORY: Symbol('TENANT_BILLING_PROFILE_REPOSITORY'),
  CUSTOMER_REPOSITORY: Symbol('CUSTOMER_REPOSITORY'),
  SERVICE_REPOSITORY: Symbol('SERVICE_REPOSITORY'),
  RESOURCE_REPOSITORY: Symbol('RESOURCE_REPOSITORY'),
  SCHEDULE_SLOT_REPOSITORY: Symbol('SCHEDULE_SLOT_REPOSITORY'),
  AGENDA_SNAPSHOT_REPOSITORY: Symbol('AGENDA_SNAPSHOT_REPOSITORY'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  JWT_TOKEN_GENERATOR: Symbol('JWT_TOKEN_GENERATOR'),
} as const;
